### ISSUE TITLE
Implementation Method of NLQ

### ISSUE THREAD

**Issue by krkrkrrk** [OpenGVLab/ego4d-eccv2022-solutions#17]
Hello,

The report mentions that the NLQ is based on GroundNLQ, but could you explain specifically how it is implemented?  
Are you replacing the InternVideo features with EgoVideo features?  
If so, I would like to conduct a replication experiment using the GroundNLQ code. Could you explain the steps for replacing InternVideo features with EgoVideo features?

**Comment by ayiyayi** [comment]
Hello krkrkrrk,

Thank you for your question! I’m happy to clarify.

1. We use EgoVideo features for both pretraining and fine-tuning. To replace the features, you’ll need to update the paths in the configuration file. Specifically, modify the following entries:

```yaml
dataset:
  video_feat_dir: your_feat_dir,
  text_feat_dir: your_text_feat_dir,
  val_text_feat_dir: your_val_text_feat_dir
```

2. Additionally, you will need to adjust the `_get_query_feat_by_qid()` and `_get_video_feat_by_vid()` functions in `libs/datasets/ego4d_loader.py` to read the data from the `.pt` format, which is used for EgoVideo features.
